"""Add due_date to Loan

Revision ID: 4aa0e0d7e4c0
Revises: 8c32b5eb40d3
Create Date: 2025-06-19 23:50:13.567265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa0e0d7e4c0'
down_revision = '8c32b5eb40d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
